version: "3.9"
name: ArcheologyAIbot

services:
  tg-service:
    image: tg-service:1.0.8
    env_file:
      - .env_docker
    build:
      context: ./telegram
      dockerfile: ./Dockerfile
    container_name: archeology-tg-backend
#    environment:
#      -DB_PATH: app/database/images_blob.db  # Путь к файлу SQLite (относительно)
#      -DADATA_TOKEN: ${DADATA_TOKEN}
#      -TG_TOKEN: ${TG_TOKEN}
#    ports:
#      - "5000:5000"
    volumes:
      - ./telegram/database:/app/database
    networks:
      - ArcheologyAIbot-network
    restart: unless-stopped

  ai-service:
    image: ai-service:1.0.1
    env_file:
      - .env_ai
    build:
      context: ./AI
      dockerfile: ./Dockerfile
    container_name: archeology-ai-backend
    ports:
      - "5000:5000"
      - "8190:8190"
    volumes:
      - ./databases:/app/databases
      - ./databases:/app/databases
    networks:
      - ArcheologyAIbot-network
    restart: unless-stopped

networks:
  ArcheologyAIbot-network:
    external: false
